openapi: 3.0.0
x-stoplight:
  id: f8jufnjqmp82d
info:
  title: FlixFlex-api
  version: 1.0.0
servers:
  - url: "http://127.0.0.1:8000"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: movies
  - name: TV
  - name: account
  - name: Authentication
paths:
  /api/register:
    post:
      tags:
        - Authentication
      summary: register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                password:
                  type: string
              x-examples:
                Example 1:
                  name: user
                  password: "12345678"
        description: |-
          {
              "name": "user",
              "password":"12345678"
          }
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: object
                    properties:
                      name:
                        type: array
                        items:
                          type: string
                      password:
                        type: array
                        items:
                          type: string
                x-examples:
                  Example 1:
                    message: The name field is required. (and 1 more error)
                    errors:
                      name:
                        - The name field is required.
                      password:
                        - The password field is required.
              examples:
                Example 1:
                  value:
                    message: string
                    errors:
                      name:
                        - string
                      password:
                        - string
  /account/favorites:
    get:
      summary: favorites
      tags:
        - account
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    media_id:
                      type: integer
                    user_id:
                      type: integer
                    popularity:
                      type: number
                    title:
                      type: string
                    overview:
                      type: string
                    poster_path:
                      type: string
                    vote_average:
                      type: string
                    release_date:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                x-examples:
                  Example 1:
                    - id: 2
                      media_id: 550
                      user_id: 1
                      popularity: 69.33
                      title: Fight Club
                      overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.'
                      poster_path: /pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg
                      vote_average: "8.4"
                      release_date: "1999-10-15T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:40.000000Z"
                      updated_at: "2023-02-25T14:28:40.000000Z"
                    - id: 3
                      media_id: 551
                      user_id: 1
                      popularity: 18.19
                      title: The Poseidon Adventure
                      overview: "When their ocean liner capsizes, a group of passengers struggle to survive and escape."
                      poster_path: /6RGiA5BfhelU9zoD0b1GAG4GWWf.jpg
                      vote_average: "7.1"
                      release_date: "1972-12-13T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:47.000000Z"
                      updated_at: "2023-02-25T14:28:47.000000Z"
              examples:
                Example 1:
                  value:
                    - id: 0
                      media_id: 0
                      user_id: 0
                      popularity: 0
                      title: string
                      overview: string
                      poster_path: string
                      vote_average: string
                      release_date: string
                      created_at: string
                      updated_at: string
      operationId: get-account-favorites
      description: "As a user, I should be able to view the list of my favorite movies and series"
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
          description: bearer token
    parameters: []
  "/api/account/mark-as-favorite/{media_id}":
    post:
      tags:
        - account
      summary: mark-as-favorite
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                media_type:
                  type: string
                media_id:
                  type: integer
              x-examples:
                Example 1:
                  media_type: movie
                  media_id: 552
            examples:
              Example 1:
                value:
                  user_id: 0
                  media_id: 0
                  popularity: 0
                  title: string
                  overview: string
                  vote_average: 0
                  poster_path: string
                  release_date: string
                  updated_at: string
                  created_at: string
                  id: 0
      security:
        - bearerAuth: []
      parameters:
        - name: Accept
          in: header
          schema:
            type: string
          example: application/json
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    media_id:
                      type: integer
                    user_id:
                      type: integer
                    popularity:
                      type: number
                    title:
                      type: string
                    overview:
                      type: string
                    poster_path:
                      type: string
                    vote_average:
                      type: string
                    release_date:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                x-examples:
                  Example 1:
                    - id: 2
                      media_id: 550
                      user_id: 1
                      popularity: 69.33
                      title: Fight Club
                      overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.'
                      poster_path: /pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg
                      vote_average: "8.4"
                      release_date: "1999-10-15T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:40.000000Z"
                      updated_at: "2023-02-25T14:28:40.000000Z"
                    - id: 3
                      media_id: 551
                      user_id: 1
                      popularity: 18.19
                      title: The Poseidon Adventure
                      overview: "When their ocean liner capsizes, a group of passengers struggle to survive and escape."
                      poster_path: /6RGiA5BfhelU9zoD0b1GAG4GWWf.jpg
                      vote_average: "7.1"
                      release_date: "1972-12-13T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:47.000000Z"
                      updated_at: "2023-02-25T14:28:47.000000Z"
              examples:
                Example 1:
                  value:
                    - id: 0
                      media_id: 0
                      user_id: 0
                      popularity: 0
                      title: string
                      overview: string
                      poster_path: string
                      vote_average: string
                      release_date: string
                      created_at: string
                      updated_at: string
      description: "As a user, I should be able to add a movie or a series to my favorites list"
    parameters:
      - schema:
          type: string
        name: media_id
        in: path
        required: true
  "/api/account/delete-favorite/{favorite_id}":
    delete:
      tags:
        - account
      summary: delete from favorite
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
      description: "As a user, I should be able to delete a movie or a series from my favorites list"
    parameters:
      - schema:
          type: string
        name: favorite_id
        in: path
        required: true
  /movies:
    get:
      summary: get movies
      tags:
        - movies
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    media_id:
                      type: integer
                    user_id:
                      type: integer
                    popularity:
                      type: number
                    title:
                      type: string
                    overview:
                      type: string
                    poster_path:
                      type: string
                    vote_average:
                      type: string
                    release_date:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                x-examples:
                  Example 1:
                    - id: 2
                      media_id: 550
                      user_id: 1
                      popularity: 69.33
                      title: Fight Club
                      overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.'
                      poster_path: /pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg
                      vote_average: "8.4"
                      release_date: "1999-10-15T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:40.000000Z"
                      updated_at: "2023-02-25T14:28:40.000000Z"
                    - id: 3
                      media_id: 551
                      user_id: 1
                      popularity: 18.19
                      title: The Poseidon Adventure
                      overview: "When their ocean liner capsizes, a group of passengers struggle to survive and escape."
                      poster_path: /6RGiA5BfhelU9zoD0b1GAG4GWWf.jpg
                      vote_average: "7.1"
                      release_date: "1972-12-13T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:47.000000Z"
                      updated_at: "2023-02-25T14:28:47.000000Z"
              examples:
                Example 1:
                  value:
                    - id: 0
                      media_id: 0
                      user_id: 0
                      popularity: 0
                      title: string
                      overview: string
                      poster_path: string
                      vote_average: string
                      release_date: string
                      created_at: string
                      updated_at: string
      operationId: get-movies
      parameters:
        - schema:
            type: string
          in: query
          name: page
          description: number of the page
        - schema:
            type: string
          in: query
          name: language
          description: laguage of the movie
        - schema:
            type: string
          in: query
          name: sort_by
          description: criteria
        - schema:
            type: boolean
          in: query
          name: include_adult
        - schema:
            type: boolean
          in: query
          name: include_video
        - schema:
            type: string
          in: query
          name: with_watch_monetization_types
      description: |-
        As a user, I should be able to view the list of movies and on different
        page

        As a user, I should be able to view, in the movies all the
        movies available in batches of 10
  /movies/top-rated:
    get:
      summary: get top rated movies
      tags:
        - movies
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    media_id:
                      type: integer
                    user_id:
                      type: integer
                    popularity:
                      type: number
                    title:
                      type: string
                    overview:
                      type: string
                    poster_path:
                      type: string
                    vote_average:
                      type: string
                    release_date:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                x-examples:
                  Example 1:
                    - id: 2
                      media_id: 550
                      user_id: 1
                      popularity: 69.33
                      title: Fight Club
                      overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.'
                      poster_path: /pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg
                      vote_average: "8.4"
                      release_date: "1999-10-15T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:40.000000Z"
                      updated_at: "2023-02-25T14:28:40.000000Z"
                    - id: 3
                      media_id: 551
                      user_id: 1
                      popularity: 18.19
                      title: The Poseidon Adventure
                      overview: "When their ocean liner capsizes, a group of passengers struggle to survive and escape."
                      poster_path: /6RGiA5BfhelU9zoD0b1GAG4GWWf.jpg
                      vote_average: "7.1"
                      release_date: "1972-12-13T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:47.000000Z"
                      updated_at: "2023-02-25T14:28:47.000000Z"
              examples:
                Example 1:
                  value:
                    - id: 0
                      media_id: 0
                      user_id: 0
                      popularity: 0
                      title: string
                      overview: string
                      poster_path: string
                      vote_average: string
                      release_date: string
                      created_at: string
                      updated_at: string
      operationId: get-movie-video
      description: |-
        As a user, I should be able to view the list of the top 5 movies in a
        dedicated section on the movies and series pages
    parameters: []
  /movies/id/detail:
    get:
      summary: get movie detail
      tags:
        - movies
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    media_id:
                      type: integer
                    user_id:
                      type: integer
                    popularity:
                      type: number
                    title:
                      type: string
                    overview:
                      type: string
                    poster_path:
                      type: string
                    vote_average:
                      type: string
                    release_date:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                x-examples:
                  Example 1:
                    - id: 2
                      media_id: 550
                      user_id: 1
                      popularity: 69.33
                      title: Fight Club
                      overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.'
                      poster_path: /pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg
                      vote_average: "8.4"
                      release_date: "1999-10-15T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:40.000000Z"
                      updated_at: "2023-02-25T14:28:40.000000Z"
                    - id: 3
                      media_id: 551
                      user_id: 1
                      popularity: 18.19
                      title: The Poseidon Adventure
                      overview: "When their ocean liner capsizes, a group of passengers struggle to survive and escape."
                      poster_path: /6RGiA5BfhelU9zoD0b1GAG4GWWf.jpg
                      vote_average: "7.1"
                      release_date: "1972-12-13T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:47.000000Z"
                      updated_at: "2023-02-25T14:28:47.000000Z"
              examples:
                Example 1:
                  value:
                    - id: 0
                      media_id: 0
                      user_id: 0
                      popularity: 0
                      title: string
                      overview: string
                      poster_path: string
                      vote_average: string
                      release_date: string
                      created_at: string
                      updated_at: string
      operationId: get-movies-top-rated
      description: "As a user, I should be able to view the details of a movie"
    parameters: []
  /movies/search:
    get:
      summary: search movies
      tags:
        - movies
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    media_id:
                      type: integer
                    user_id:
                      type: integer
                    popularity:
                      type: number
                    title:
                      type: string
                    overview:
                      type: string
                    poster_path:
                      type: string
                    vote_average:
                      type: string
                    release_date:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                x-examples:
                  Example 1:
                    - id: 2
                      media_id: 550
                      user_id: 1
                      popularity: 69.33
                      title: Fight Club
                      overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.'
                      poster_path: /pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg
                      vote_average: "8.4"
                      release_date: "1999-10-15T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:40.000000Z"
                      updated_at: "2023-02-25T14:28:40.000000Z"
                    - id: 3
                      media_id: 551
                      user_id: 1
                      popularity: 18.19
                      title: The Poseidon Adventure
                      overview: "When their ocean liner capsizes, a group of passengers struggle to survive and escape."
                      poster_path: /6RGiA5BfhelU9zoD0b1GAG4GWWf.jpg
                      vote_average: "7.1"
                      release_date: "1972-12-13T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:47.000000Z"
                      updated_at: "2023-02-25T14:28:47.000000Z"
              examples:
                Example 1:
                  value:
                    - id: 0
                      media_id: 0
                      user_id: 0
                      popularity: 0
                      title: string
                      overview: string
                      poster_path: string
                      vote_average: string
                      release_date: string
                      created_at: string
                      updated_at: string
      operationId: get-movie-videos
      description: "As a user, I should be able to search for movies"
    parameters: []
  /movies/id/videos:
    get:
      summary: movie videos
      tags:
        - movies
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        iso_639_1:
                          type: string
                        iso_3166_1:
                          type: string
                        name:
                          type: string
                        key:
                          type: string
                        site:
                          type: string
                        size:
                          type: integer
                        type:
                          type: string
                        official:
                          type: boolean
                        published_at:
                          type: string
                        id:
                          type: string
                x-examples:
                  Example 1:
                    id: 550
                    results:
                      - iso_639_1: en
                        iso_3166_1: US
                        name: "Fight Club (1999) Trailer - Starring Brad Pitt, Edward Norton, Helena Bonham Carter"
                        key: O-b2VfmmbyA
                        site: YouTube
                        size: 720
                        type: Trailer
                        official: false
                        published_at: "2016-03-05T02:03:14.000Z"
                        id: 639d5326be6d88007f170f44
                      - iso_639_1: en
                        iso_3166_1: US
                        name: "#TBT Trailer"
                        key: BdJKm16Co6M
                        site: YouTube
                        size: 1080
                        type: Trailer
                        official: true
                        published_at: "2014-10-02T19:20:22.000Z"
                        id: 5c9294240e0a267cd516835f
              examples:
                Example 1:
                  value:
                    id: 0
                    results:
                      - iso_639_1: string
                        iso_3166_1: string
                        name: string
                        key: string
                        site: string
                        size: 0
                        type: string
                        official: true
                        published_at: string
                        id: string
      operationId: get-movies-id-videos
      description: "As a user, I should be able to watch the trailer of a movie"
  /tv:
    get:
      summary: tvs list
      tags:
        - TV
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    media_id:
                      type: integer
                    user_id:
                      type: integer
                    popularity:
                      type: number
                    title:
                      type: string
                    overview:
                      type: string
                    poster_path:
                      type: string
                    vote_average:
                      type: string
                    release_date:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                x-examples:
                  Example 1:
                    - id: 2
                      media_id: 550
                      user_id: 1
                      popularity: 69.33
                      title: Fight Club
                      overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.'
                      poster_path: /pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg
                      vote_average: "8.4"
                      release_date: "1999-10-15T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:40.000000Z"
                      updated_at: "2023-02-25T14:28:40.000000Z"
                    - id: 3
                      media_id: 551
                      user_id: 1
                      popularity: 18.19
                      title: The Poseidon Adventure
                      overview: "When their ocean liner capsizes, a group of passengers struggle to survive and escape."
                      poster_path: /6RGiA5BfhelU9zoD0b1GAG4GWWf.jpg
                      vote_average: "7.1"
                      release_date: "1972-12-13T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:47.000000Z"
                      updated_at: "2023-02-25T14:28:47.000000Z"
              examples:
                Example 1:
                  value:
                    - id: 0
                      media_id: 0
                      user_id: 0
                      popularity: 0
                      title: string
                      overview: string
                      poster_path: string
                      vote_average: string
                      release_date: string
                      created_at: string
                      updated_at: string
      operationId: get-tv
      parameters:
        - schema:
            type: string
          in: query
          name: page
          description: number of the page
        - schema:
            type: string
          in: query
          name: language
          description: laguage of the movie
        - schema:
            type: string
          in: query
          name: sort_by
          description: criteria
        - schema:
            type: boolean
          in: query
          name: include_adult
        - schema:
            type: boolean
          in: query
          name: include_video
        - schema:
            type: string
          in: query
          name: with_watch_monetization_types
      description: |-
        As a user, I should be able to view the list ofseries on different page
        As a user, I should be able to view, in the series all the movies available in batches of 10
    parameters: []
  /tv/top-rated:
    get:
      summary: get top rated series
      tags:
        - TV
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    media_id:
                      type: integer
                    user_id:
                      type: integer
                    popularity:
                      type: number
                    title:
                      type: string
                    overview:
                      type: string
                    poster_path:
                      type: string
                    vote_average:
                      type: string
                    release_date:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                x-examples:
                  Example 1:
                    - id: 2
                      media_id: 550
                      user_id: 1
                      popularity: 69.33
                      title: Fight Club
                      overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.'
                      poster_path: /pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg
                      vote_average: "8.4"
                      release_date: "1999-10-15T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:40.000000Z"
                      updated_at: "2023-02-25T14:28:40.000000Z"
                    - id: 3
                      media_id: 551
                      user_id: 1
                      popularity: 18.19
                      title: The Poseidon Adventure
                      overview: "When their ocean liner capsizes, a group of passengers struggle to survive and escape."
                      poster_path: /6RGiA5BfhelU9zoD0b1GAG4GWWf.jpg
                      vote_average: "7.1"
                      release_date: "1972-12-13T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:47.000000Z"
                      updated_at: "2023-02-25T14:28:47.000000Z"
              examples:
                Example 1:
                  value:
                    - id: 0
                      media_id: 0
                      user_id: 0
                      popularity: 0
                      title: string
                      overview: string
                      poster_path: string
                      vote_average: string
                      release_date: string
                      created_at: string
                      updated_at: string
      operationId: get-tv-detail
      description: |-
        As a user, I should be able to view the list of the top 5 series in a
        dedicated section on the movies and series pages
    parameters: []
  /tv/id/detail:
    get:
      summary: get serie detail
      tags:
        - TV
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    media_id:
                      type: integer
                    user_id:
                      type: integer
                    popularity:
                      type: number
                    title:
                      type: string
                    overview:
                      type: string
                    poster_path:
                      type: string
                    vote_average:
                      type: string
                    release_date:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                x-examples:
                  Example 1:
                    - id: 2
                      media_id: 550
                      user_id: 1
                      popularity: 69.33
                      title: Fight Club
                      overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.'
                      poster_path: /pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg
                      vote_average: "8.4"
                      release_date: "1999-10-15T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:40.000000Z"
                      updated_at: "2023-02-25T14:28:40.000000Z"
                    - id: 3
                      media_id: 551
                      user_id: 1
                      popularity: 18.19
                      title: The Poseidon Adventure
                      overview: "When their ocean liner capsizes, a group of passengers struggle to survive and escape."
                      poster_path: /6RGiA5BfhelU9zoD0b1GAG4GWWf.jpg
                      vote_average: "7.1"
                      release_date: "1972-12-13T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:47.000000Z"
                      updated_at: "2023-02-25T14:28:47.000000Z"
              examples:
                Example 1:
                  value:
                    - id: 0
                      media_id: 0
                      user_id: 0
                      popularity: 0
                      title: string
                      overview: string
                      poster_path: string
                      vote_average: string
                      release_date: string
                      created_at: string
                      updated_at: string
      operationId: get-tv-top-rated
      description: "As a user, I should be able to view the details of a series"
    parameters: []
  /tv/id/video:
    get:
      summary: get tv videos
      tags:
        - TV
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        iso_639_1:
                          type: string
                        iso_3166_1:
                          type: string
                        name:
                          type: string
                        key:
                          type: string
                        site:
                          type: string
                        size:
                          type: integer
                        type:
                          type: string
                        official:
                          type: boolean
                        published_at:
                          type: string
                        id:
                          type: string
                x-examples:
                  Example 1:
                    id: 550
                    results:
                      - iso_639_1: en
                        iso_3166_1: US
                        name: "Fight Club (1999) Trailer - Starring Brad Pitt, Edward Norton, Helena Bonham Carter"
                        key: O-b2VfmmbyA
                        site: YouTube
                        size: 720
                        type: Trailer
                        official: false
                        published_at: "2016-03-05T02:03:14.000Z"
                        id: 639d5326be6d88007f170f44
                      - iso_639_1: en
                        iso_3166_1: US
                        name: "#TBT Trailer"
                        key: BdJKm16Co6M
                        site: YouTube
                        size: 1080
                        type: Trailer
                        official: true
                        published_at: "2014-10-02T19:20:22.000Z"
                        id: 5c9294240e0a267cd516835f
              examples:
                Example 1:
                  value:
                    id: 0
                    results:
                      - iso_639_1: string
                        iso_3166_1: string
                        name: string
                        key: string
                        site: string
                        size: 0
                        type: string
                        official: true
                        published_at: string
                        id: string
      operationId: get-tv-id-videos
      description: "As a user, I should be able to watch the trailer of a serie"
    parameters: []
  /tv/search:
    get:
      summary: search tv
      tags:
        - TV
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    media_id:
                      type: integer
                    user_id:
                      type: integer
                    popularity:
                      type: number
                    title:
                      type: string
                    overview:
                      type: string
                    poster_path:
                      type: string
                    vote_average:
                      type: string
                    release_date:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                x-examples:
                  Example 1:
                    - id: 2
                      media_id: 550
                      user_id: 1
                      popularity: 69.33
                      title: Fight Club
                      overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.'
                      poster_path: /pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg
                      vote_average: "8.4"
                      release_date: "1999-10-15T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:40.000000Z"
                      updated_at: "2023-02-25T14:28:40.000000Z"
                    - id: 3
                      media_id: 551
                      user_id: 1
                      popularity: 18.19
                      title: The Poseidon Adventure
                      overview: "When their ocean liner capsizes, a group of passengers struggle to survive and escape."
                      poster_path: /6RGiA5BfhelU9zoD0b1GAG4GWWf.jpg
                      vote_average: "7.1"
                      release_date: "1972-12-13T00:00:00.000000Z"
                      created_at: "2023-02-25T14:28:47.000000Z"
                      updated_at: "2023-02-25T14:28:47.000000Z"
              examples:
                Example 1:
                  value:
                    - id: 0
                      media_id: 0
                      user_id: 0
                      popularity: 0
                      title: string
                      overview: string
                      poster_path: string
                      vote_average: string
                      release_date: string
                      created_at: string
                      updated_at: string
      operationId: get-tv-search
      description: "As a user, I should be able to search for series"
    parameters: []
